# Cloudflare Pages Configuration
# Este projeto usa Cloudflare Pages Functions (não Workers standalone)
# O frontend em public/ é servido diretamente
# As functions em functions/api/ são executadas automaticamente
name = "mapeamento-ooh"
# Build output directory
pages_build_output_dir = "public"

# Compatibilidade
compatibility_date = "2024-01-01"

# Variáveis de ambiente devem ser configuradas via Cloudflare Pages Dashboard:
# Settings > Environment Variables
#
# Variáveis necessárias:
# - NOTION_TOKEN: Token de integração do Notion
# - GOOGLE_DRIVE_CREDENTIALS: Credentials JSON do service account (futuro)
